application: rfc6265biz
version: prerelease-01
runtime: go
api_version: go1

handlers:
- url: /tests/
  static_files: static/tests/index.html
  upload: static/tests/index.html
- url: /tests
  static_dir: static/tests
- url: /.*
  script: _go_app

